### ISSUE TITLE
How to migrate from 5.1.1 to 5.1.1 + multiple?

### ISSUE THREAD

**Issue by jerryyip** [ionos-cloud/reprepro#10]
It said that "The multiple-versions reprepro supports migrating from 5.1.1 to 5.1.1 + multiple versions " in the readme. But I can't find a way to make it in the document.
Can anyone point me out?
Thanks very much!

**Comment by bdrung** [comment]
The first time the database is opened by reprepro with multiple versions support, the database will be upgraded from the upstream layout to the multiple versions layout. So you do not have to explicitly do anything.
