### ISSUE TITLE
Is there a way to "Limit: x" different components of a distribution differently?

### ISSUE THREAD

**Issue by andywolk** [ionos-cloud/reprepro#11]

**Comment by bdrung** [comment]
No, there is no way to limit different components for the same suite, but you could use different suites instead.

**Comment by andywolk** [comment]
Would be nice to have that functionality.
What about `|x` after each item?:
```
Components: main|10 contrib non-free|1
Limit: 5
```
And `main|10` overrides `5`.

**Comment by bdrung** [comment]
Adding `|x` to each item is an unconventional way to configure it, but I have no better idea how to support this setup in the configuration.

**Comment by andywolk** [comment]
Another option:
```
Components: main contrib non-free
Limit: 5 main|10 non-free|1
```
But this way it will be harder to make limits for other things like architecture.

```
Architectures: source amd64 i386 arm64
Components: main contrib non-free
Limit: 5 main|10 arm64|non-free|1 amd64||5
```
On the other hand this way it's way flexible.

**Comment by bdrung** [comment]
Another option:
```
Components: main contrib non-free
Limit: main=5 non-free=10 1
```

**Comment by andywolk** [comment]
Let me apply combinations to your option:
```
Architectures: source amd64 i386 arm64
Components: main contrib non-free
Limit: 5 main=10 arm64|non-free=1 amd64|=5
```
