### ISSUE TITLE
remove a specific version of a package

### ISSUE THREAD

**Issue by Eng3l** [ionos-cloud/reprepro#17]
This fork of reprepro works fine for me, but sometimes I need to remove a specific version of a package from a component but there is no such option.
I have multiple version of a package and those packages can have multiple status (stable, updates, releases), If I made a mistake and change the component of a package there is no option to rollback in this case just remove the package.

Thanks.

**Comment by bdrung** [comment]
You can specify a version when removing a package. Example:
```
reprepro remove bullseye example-package=1.0.2
```

Does that solve your use case?

**Comment by Eng3l** [comment]
Yes, it works fine. I fell so dummy for not trying that, but I think is no documented at all.

**Comment by bdrung** [comment]
It's documented in the man page: https://github.com/ionos-enterprise/reprepro/blob/multiple-versions-debian/docs/reprepro.1

```
remove codename package-names=version ...
```

All changes done in our branch are reflected in the man page.
