### ISSUE TITLE
Few issues/concerns 

### ISSUE THREAD

**Issue by iGuy5** [ionos-cloud/reprepro#2]
Hi,

This is awesome thank you. I'm finding that using the ls or list command gives me a "segmentation fault" is there a way I can send you a log of sorts ?

I'm also finding by adding the multi feature it's not very intuitive to remove Packages, I think it would be much easier to have a command line option which you can specify if you want to replace the package if it already exists in the repo or not. Or if reprepro supported search queries like 

remove somepackage (<<3.0) 

Rather than having to specify each version to remove. 

I think having a commandline option like --multi, allows multiple versions of the same package in a repo, if the option is not used old versions of the package would be removed when a new is imported. 

Thanks

**Comment by bdrung** [comment]
To remove multiple package version, you can use listfilter/removefilter:

```
reprepro listfilter $distro 'package (= somepackage), version (<< 3.0)'
reprepro removefilter $distro 'package (= somepackage), version (<< 3.0)'
```

Making each repo configurable for single/multi packages makes sense.

**Comment by bdrung** [comment]
When you run into a segmentation fault, can you re-run with gdb and open a ticket with a full stacktrace? Can you reproduce the segmentation fault? Can you come up with a small test case (and a fresh repo)?

**Comment by iGuy5** [comment]
Thank you for the reply, I will try listfilter and removefilter.

IIRC the segmentation fault was because I was trying to use a db from the previous reprepro without multi version support, once I started with a fresh db I didn't run into any issues. Would this be the case the db would have had to be created by the new multi version supported reprepro ?

Thanks!

**Comment by bdrung** [comment]
Yes, the multi version support database has a different layout and is incompatible to the single version.

**Comment by bdrung** [comment]
The latest version (i.e. 5.1.1-multiple-versions) support updating the database layout (to the new layout which is required to support multiple versions). A downgrade is not supported. I am closing this ticket as your issues are addressed.
