### ISSUE TITLE
Require build-depend on db-util

### ISSUE THREAD

**Issue by FransUrbo** [ionos-cloud/reprepro#3]
Trying to build `5.1.1-multiple-versions` gives me:

```
./basic.sh
test_empty
I: Calling /usr/src/tmp/reprepro-profitbricks/reprepro -b ./testrepo list buster
./basic.sh: 28: /usr/bin/shunit2: db_verify: not found
ASSERT:BerkeleyDB 'packages.db' is broken.
[etc]
```

Adding `db-util` to the `Build-Depends` line in `debian/control` helped.

**Comment by FransUrbo** [comment]
Oh, I also had to make a (soft) link between `/usr/bin/db5.3_verify` and `/usr/bin/db_verify`.

**Comment by bdrung** [comment]
Thanks. I added the build dependency to the relevant commit and pushed to 5.1.1-multiple-versions branch.

The db-util package will create the symlink to the correct dbX.Y_verify command.
