### ISSUE TITLE
Please add information about the multi-version changes

### ISSUE THREAD

**Issue by FransUrbo** [ionos-cloud/reprepro#4]
Could you write a `README-multiple-versions` file which explains the theory of these additions, what's needed (upgrade path etc) and how to use it?

**Comment by bdrung** [comment]
I added a README.md. Please reopen the bug if you have more question that should be mentioned in the readme.

**Comment by FransUrbo** [comment]
I can't seem to be able to reopen the issue...

Could you add configuration options (how to set this up) as well? I know there's a `Limit: #` option, but what else is there?

**Comment by bdrung** [comment]
There are new two new options: Limit and Archive. They are described in the man page. The setup is not different to the upstream version.

**Comment by thehesiod** [comment]
this was really confusing for me too, I thought it would just automatically start working.  I think a little blurb on the first page of the repo would be nice stating you need to enable ... to enable multiple version support

**Comment by bdrung** [comment]
Documented that you have to set the `Limit` option: https://github.com/ionos-enterprise/reprepro#how-to-keep-multiple-versions

All new commands and options are listed in https://github.com/ionos-enterprise/reprepro#release-notes
